### ISSUE TITLE
Trainingsdaten doppelt eingeführt

### ISSUE THREAD

**Issue by jbol14** [jbol14/wiinfss2019#2]
Ich habe in meinem Teil Trainingsdaten eingeführt und du in deinem auch. Deine Einführung ist ausführlicher, wir brauchen die aber definitiv schon früher.

**Comment by stevenM14** [comment]
doppelt hält besser... ne wenn du die früher brauchst dann schau mal ob du mit meiner und deiner definition nicht noch ne bessere hinbekommst. Ich verweise dann in meinem Teil auf das Kapitel

**Comment by jbol14** [comment]
Trainingsdaten im Abschnitt Lernen mit Lehrer eingeführt
